version: 1.0.{build}
image:
  - Visual Studio 2019
platform:
  - x86
  - x64
environment:
  testvar: 123.456.789
  rel: 0

  matrix:
    - abc: def

    - abc: 123
build_script:
  - ps: .\test.ps1 -arg1 "$env:abc" -arg2 "$env:PLATFORM"
artifacts:
  - path: test-$(abc)-$(PLATFORM).zip
deploy:
  release: test-v$(testvar)-r$(rel)
  description: 'Test release'
  provider: GitHub
  auth_token:
    secure: z8nPPbj5OVa9q8IRsMDEzFU2FNihxXc5yp+cpx2mjy2k30JbnPUKxKztYrMT0aw9
  artifact: /.+\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
